In [1]:
import numpy as np
import pandas as pd

# Random seed set karna taaki har baar same data generate ho
np.random.seed(42)
num_rows = 5000

# 1. User Profile Features (User khud kaisa hai)
user_professions = ['Student', 'Software Engineer', 'Business Owner', 'Job Seeker']
user_profession = np.random.choice(user_professions, num_rows)

user_weaknesses = ['Study/Work Focus', 'Emotional/Trusts Easily', 'Money Management', 'Anxiety/Stress']
user_weakness = np.random.choice(user_weaknesses, num_rows)

# 2. Friend Behavioral Features (Dost ke lakshan)
helps_in_need_score = np.random.uniform(1.0, 10.0, num_rows)       # Mushkil me madad (1 se 10)
keeps_secrets_rate = np.random.uniform(10.0, 100.0, num_rows)       # Baatein gupt rakhna (%)
backbiting_frequency = np.random.randint(0, 12, num_rows)          # Piche chugli karna (Count)
calls_only_for_help = np.random.choice([0, 1], num_rows, p=[0.65, 0.35]) # Sirf kaam ke liye call karna (1=Yes, 0=No)
closest_friends_toxic_count = np.random.randint(0, 4, num_rows)    # Uske baaki dost kitne toxic hain (0 se 3)
respects_others = np.random.choice([0, 1], num_rows, p=[0.3, 0.7])  # Baaki logo ki izzat karna (1=Yes, 0=No)

# 3. Pure Mathematical Intuition for Perfect Match (Target: 1 = True Friend, 0 = Avoid/Fake)
# Sacha dost tabhi hoga jab madad score high ho, secrets safe rakhe, chugli zero ho aur uske padosi toxic na hon
match_score = (helps_in_need_score * 0.4) + (keeps_secrets_rate * 0.03) + (respects_others * 1.5) - \
              (backbiting_frequency * 0.5) - (calls_only_for_help * 2.0) - (closest_friends_toxic_count * 1.2)

# Median calculate karke perfectly balanced 1 (True Vishvasniya Friend ✅) aur 0 (Fake/Avoid 🚨) me baantna
is_perfect_friend = np.where(match_score > np.median(match_score), 1, 0)

# 4. DataFrame create karna
df_blueprint = pd.DataFrame({
    'User_Profession': user_profession,
    'User_Weakness': user_weakness,
    'Helps_In_Need_Score': np.round(helps_in_need_score, 1),
    'Keeps_Secrets_Rate': np.round(keeps_secrets_rate, 0).astype(int),
    'Backbiting_Frequency': backbiting_frequency,
    'Calls_Only_For_Help': calls_only_for_help,
    'Closest_Friends_Toxic_Count': closest_friends_toxic_count,
    'Respects_Others': respects_others,
    'Is_Perfect_Friend': is_perfect_friend
})

# Jupyter notebook me top 5 rows dekhna
df_blueprint.head()

,User_Profession,User_Weakness,Helps_In_Need_Score,Keeps_Secrets_Rate,Backbiting_Frequency,Calls_Only_For_Help,Closest_Friends_Toxic_Count,Respects_Others,Is_Perfect_Friend
0,Business Owner,Money Management,4.5,44,11,0,3,1,0
1,Job Seeker,Money Management,5.3,40,5,1,1,1,0
2,Student,Money Management,8.7,26,3,0,2,1,1
3,Business Owner,Money Management,4.1,65,3,0,0,1,1
4,Business Owner,Anxiety/Stress,8.8,53,10,0,2,1,0

In [2]:
df_blueprint.shape

(5000, 9)

In [3]:
df_blueprint.isnull().sum()

User_Profession                0
User_Weakness                  0
Helps_In_Need_Score            0
Keeps_Secrets_Rate             0
Backbiting_Frequency           0
Calls_Only_For_Help            0
Closest_Friends_Toxic_Count    0
Respects_Others                0
Is_Perfect_Friend              0
dtype: int64

In [4]:
df_blueprint.describe

<bound method NDFrame.describe of         User_Profession            User_Weakness  Helps_In_Need_Score  \
0        Business Owner         Money Management                  4.5
1            Job Seeker         Money Management                  5.3
2               Student         Money Management                  8.7
3        Business Owner         Money Management                  4.1
4        Business Owner           Anxiety/Stress                  8.8
...                 ...                      ...                  ...
4995            Student           Anxiety/Stress                  8.7
4996  Software Engineer         Money Management                  9.1
4997     Business Owner  Emotional/Trusts Easily                  9.5
4998  Software Engineer  Emotional/Trusts Easily                  4.6
4999         Job Seeker         Study/Work Focus                  3.0

      Keeps_Secrets_Rate  Backbiting_Frequency  Calls_Only_For_Help  \
0                     44                    11                    0
1                     40                     5                    1
2                     26                     3                    0
3                     65                     3                    0
4                     53                    10                    0
...                  ...                   ...                  ...
4995                  69                     8                    1
4996                  26                     1                    1
4997                  15                     9                    0
4998                  71                     9                    1
4999                  33                     9                    1

      Closest_Friends_Toxic_Count  Respects_Others  Is_Perfect_Friend
0                               3                1                  0
1                               1                1                  0
2                               2                1                  1
3                               0                1                  1
4                               2                1                  0
...                           ...              ...                ...
4995                            0                1                  1
4996                            3                1                  1
4997                            1                1                  1
4998                            3                0                  0
4999                            3                1                  0

[5000 rows x 9 columns]>

In [10]:

print("--- DATASET INFORMATION ---")
df_blueprint.info()
print("\n--- TARGET VARIABLE DISTRIBUTION ---")
print(df_blueprint['Is_Perfect_Friend'].value_counts())
print("\n--- MISSING VALUES CHECK ---")
print(df_blueprint.isnull().sum())

--- DATASET INFORMATION ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   User_Profession              5000 non-null   object
 1   User_Weakness                5000 non-null   object
 2   Helps_In_Need_Score          5000 non-null   float64
 3   Keeps_Secrets_Rate           5000 non-null   int64
 4   Backbiting_Frequency         5000 non-null   int32
 5   Calls_Only_For_Help          5000 non-null   int64
 6   Closest_Friends_Toxic_Count  5000 non-null   int32
 7   Respects_Others              5000 non-null   int64
 8   Is_Perfect_Friend            5000 non-null   int64
dtypes: float64(1), int32(2), int64(4), object(2)
memory usage: 312.6+ KB

--- TARGET VARIABLE DISTRIBUTION ---
Is_Perfect_Friend
0    2500
1    2500
Name: count, dtype: int64

--- MISSING VALUES CHECK ---
User_Profession                0
User_Weakness                  0
Helps_In_Need_Score            0
Keeps_Secrets_Rate             0
Backbiting_Frequency           0
Calls_Only_For_Help            0
Closest_Friends_Toxic_Count    0
Respects_Others                0
Is_Perfect_Friend              0
dtype: int64

In [5]:

print("--- BLUEPRINT DATASET STATISTICAL SUMMARY ---")
df_blueprint.describe().T

--- BLUEPRINT DATASET STATISTICAL SUMMARY ---

,count,mean,std,min,25%,50%,75%,max
Helps_In_Need_Score,5000.0,5.42346,2.570381,1.0,3.2,5.4,7.6,10.0
Keeps_Secrets_Rate,5000.0,55.12260,26.168969,10.0,32.0,55.0,78.0,100.0
Backbiting_Frequency,5000.0,5.45100,3.459768,0.0,2.0,5.0,8.0,11.0
Calls_Only_For_Help,5000.0,0.35120,0.477393,0.0,0.0,0.0,1.0,1.0
Closest_Friends_Toxic_Count,5000.0,1.50380,1.111140,0.0,1.0,2.0,2.0,3.0
Respects_Others,5000.0,0.71720,0.450405,0.0,0.0,1.0,1.0,1.0
Is_Perfect_Friend,5000.0,0.50000,0.500050,0.0,0.0,0.5,1.0,1.0

In [6]:

df_encoded = pd.get_dummies(df_blueprint, columns=['User_Profession', 'User_Weakness'], drop_first=False)
df_encoded = df_encoded.astype({col: int for col in df_encoded.columns if df_encoded[col].dtype == 'bool'})
print(f"Naye encoded dataset ka size: {df_encoded.shape} (Rows, Columns)")
df_encoded.head(3)

Naye encoded dataset ka size: (5000, 15) (Rows, Columns)

,Helps_In_Need_Score,Keeps_Secrets_Rate,Backbiting_Frequency,Calls_Only_For_Help,Closest_Friends_Toxic_Count,Respects_Others,Is_Perfect_Friend,User_Profession_Business Owner,User_Profession_Job Seeker,User_Profession_Software Engineer,User_Profession_Student,User_Weakness_Anxiety/Stress,User_Weakness_Emotional/Trusts Easily,User_Weakness_Money Management,User_Weakness_Study/Work Focus
0,4.5,44,11,0,3,1,0,1,0,0,0,0,0,1,0
1,5.3,40,5,1,1,1,0,0,1,0,0,0,0,1,0
2,8.7,26,3,0,2,1,1,0,0,0,1,0,0,1,0

In [7]:
df_blueprint.head()

,User_Profession,User_Weakness,Helps_In_Need_Score,Keeps_Secrets_Rate,Backbiting_Frequency,Calls_Only_For_Help,Closest_Friends_Toxic_Count,Respects_Others,Is_Perfect_Friend
0,Business Owner,Money Management,4.5,44,11,0,3,1,0
1,Job Seeker,Money Management,5.3,40,5,1,1,1,0
2,Student,Money Management,8.7,26,3,0,2,1,1
3,Business Owner,Money Management,4.1,65,3,0,0,1,1
4,Business Owner,Anxiety/Stress,8.8,53,10,0,2,1,0

In [8]:
df_blueprint.shape

(5000, 9)

In [9]:
from sklearn.model_selection import train_test_split
X = df_encoded.drop(columns=['Is_Perfect_Friend'])
y = df_encoded['Is_Perfect_Friend']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print("--- DATA SPLIT COMPLETE ---")
print(f"X_train (Padhai ke liye data): {X_train.shape}")
print(f"X_test (Test/Exam lene ke liye data): {X_test.shape}")
print(f"y_train (Training data ke sahi labels): {y_train.shape}")
print(f"y_test (Testing data ke sahi labels): {y_test.shape}")

--- DATA SPLIT COMPLETE ---
X_train (Padhai ke liye data): (4000, 14)
X_test (Test/Exam lene ke liye data): (1000, 14)
y_train (Training data ke sahi labels): (4000,)
y_test (Testing data ke sahi labels): (1000,)

In [10]:
df_blueprint.describe

<bound method NDFrame.describe of         User_Profession            User_Weakness  Helps_In_Need_Score  \
0        Business Owner         Money Management                  4.5
1            Job Seeker         Money Management                  5.3
2               Student         Money Management                  8.7
3        Business Owner         Money Management                  4.1
4        Business Owner           Anxiety/Stress                  8.8
...                 ...                      ...                  ...
4995            Student           Anxiety/Stress                  8.7
4996  Software Engineer         Money Management                  9.1
4997     Business Owner  Emotional/Trusts Easily                  9.5
4998  Software Engineer  Emotional/Trusts Easily                  4.6
4999         Job Seeker         Study/Work Focus                  3.0

      Keeps_Secrets_Rate  Backbiting_Frequency  Calls_Only_For_Help  \
0                     44                    11                    0
1                     40                     5                    1
2                     26                     3                    0
3                     65                     3                    0
4                     53                    10                    0
...                  ...                   ...                  ...
4995                  69                     8                    1
4996                  26                     1                    1
4997                  15                     9                    0
4998                  71                     9                    1
4999                  33                     9                    1

      Closest_Friends_Toxic_Count  Respects_Others  Is_Perfect_Friend
0                               3                1                  0
1                               1                1                  0
2                               2                1                  1
3                               0                1                  1
4                               2                1                  0
...                           ...              ...                ...
4995                            0                1                  1
4996                            3                1                  1
4997                            1                1                  1
4998                            3                0                  0
4999                            3                1                  0

[5000 rows x 9 columns]>

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("--- FEATURE SCALING COMPLETE ---")
print("Saare columns ab ek standard normal distribution (Mean=0, Std=1) mein badal chuke hain! ")

--- FEATURE SCALING COMPLETE ---
Saare columns ab ek standard normal distribution (Mean=0, Std=1) mein badal chuke hain!

In [12]:
df_blueprint.head()

,User_Profession,User_Weakness,Helps_In_Need_Score,Keeps_Secrets_Rate,Backbiting_Frequency,Calls_Only_For_Help,Closest_Friends_Toxic_Count,Respects_Others,Is_Perfect_Friend
0,Business Owner,Money Management,4.5,44,11,0,3,1,0
1,Job Seeker,Money Management,5.3,40,5,1,1,1,0
2,Student,Money Management,8.7,26,3,0,2,1,1
3,Business Owner,Money Management,4.1,65,3,0,0,1,1
4,Business Owner,Anxiety/Stress,8.8,53,10,0,2,1,0

In [13]:
df_blueprint['User_Weakness'].unique()

array(['Money Management', 'Anxiety/Stress', 'Study/Work Focus',
       'Emotional/Trusts Easily'], dtype=object)

In [14]:
df_blueprint['Helps_In_Need_Score'].unique()

array([ 4.5,  5.3,  8.7,  4.1,  8.8,  1.8,  8. ,  8.6,  2.6,  4.9,  2.5,
        7.4,  5.8,  6.7,  2.8,  2.9,  1.4,  3.9,  6. ,  7. ,  9.6,  7.5,
        9.4,  5.7,  3.3,  1.5,  2.1,  3.7,  6.1,  6.4,  4.4,  6.6,  9.7,
        9.3,  7.9,  6.3,  2.7,  5.4,  4. ,  8.2,  6.9,  3.5,  5.5,  7.6,
        1.3,  1.1,  7.7,  9.8,  6.5,  3.1,  1.7,  2. ,  8.5,  3.2,  1.6,
        6.2,  3.4,  4.8,  5. ,  3.8,  4.3,  1.9,  7.3,  3.6,  5.1,  7.8,
        9.2,  5.9,  5.6,  7.1,  4.7,  8.9,  6.8,  9.1,  2.2,  3. ,  5.2,
        2.3,  9.9,  1.2,  8.3,  9. ,  9.5,  4.2,  4.6,  2.4,  7.2,  8.4,
        8.1, 10. ,  1. ])

In [15]:
df_blueprint.head()

,User_Profession,User_Weakness,Helps_In_Need_Score,Keeps_Secrets_Rate,Backbiting_Frequency,Calls_Only_For_Help,Closest_Friends_Toxic_Count,Respects_Others,Is_Perfect_Friend
0,Business Owner,Money Management,4.5,44,11,0,3,1,0
1,Job Seeker,Money Management,5.3,40,5,1,1,1,0
2,Student,Money Management,8.7,26,3,0,2,1,1
3,Business Owner,Money Management,4.1,65,3,0,0,1,1
4,Business Owner,Anxiety/Stress,8.8,53,10,0,2,1,0

In [16]:
df_blueprint.head()

,User_Profession,User_Weakness,Helps_In_Need_Score,Keeps_Secrets_Rate,Backbiting_Frequency,Calls_Only_For_Help,Closest_Friends_Toxic_Count,Respects_Others,Is_Perfect_Friend
0,Business Owner,Money Management,4.5,44,11,0,3,1,0
1,Job Seeker,Money Management,5.3,40,5,1,1,1,0
2,Student,Money Management,8.7,26,3,0,2,1,1
3,Business Owner,Money Management,4.1,65,3,0,0,1,1
4,Business Owner,Anxiety/Stress,8.8,53,10,0,2,1,0

In [17]:
df_blueprint.isnull().sum()

User_Profession                0
User_Weakness                  0
Helps_In_Need_Score            0
Keeps_Secrets_Rate             0
Backbiting_Frequency           0
Calls_Only_For_Help            0
Closest_Friends_Toxic_Count    0
Respects_Others                0
Is_Perfect_Friend              0
dtype: int64

In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5, weights='uniform', metric='minkowski', p=2)
print("K-Nearest Neighbors (KNN) model train ho raha hai, thoda wait karein...")
knn_model.fit(X_train_scaled, y_train)
print("KNN Model Training Successfully Complete! 🤝🎉")

K-Nearest Neighbors (KNN) model train ho raha hai, thoda wait karein...
KNN Model Training Successfully Complete! 🤝🎉

In [22]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
y_pred = knn_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("--- KNN MODEL PERFORMANCE EVALUATION ---")
print(f"Model ki Final Test Accuracy: {accuracy * 100:.2f}%\n")
print("--- DETAILED CLASSIFICATION REPORT ---")
print(classification_report(y_test, y_pred))
print("--- CONFUSION MATRIX ---")
print(confusion_matrix(y_test, y_pred))

--- KNN MODEL PERFORMANCE EVALUATION ---
Model ki Final Test Accuracy: 89.10%

--- DETAILED CLASSIFICATION REPORT ---
              precision    recall  f1-score   support

           0       0.88      0.91      0.89       500
           1       0.91      0.87      0.89       500

    accuracy                           0.89      1000
   macro avg       0.89      0.89      0.89      1000
weighted avg       0.89      0.89      0.89      1000

--- CONFUSION MATRIX ---
[[455  45]
 [ 64 436]]

In [24]:
import pickle
model_filename = 'knn_friend_blueprint_model.pkl'
with open(model_filename, 'wb') as file:
    pickle.dump(knn_model, file)
scaler_filename = 'knn_friend_blueprint_scaler.pkl'
with open(scaler_filename, 'wb') as file:
    pickle.dump(scaler, file)
features_filename = 'knn_model_features.pkl'
with open(features_filename, 'wb') as file:
    pickle.dump(list(X.columns), file)

print("--- KNN ASSETS EXPORT COMPLETE ---")
print(f"1. Model file save ho gayi: '{model_filename}'")
print(f"2. Scaler file save ho gayi: '{scaler_filename}'")
print(f"3. Features file save ho gayi: '{features_filename}'")
print("\nMera Jupyter Notebook ka pura safar 100% complete ho gaya hai! 🏁🎉")

--- KNN ASSETS EXPORT COMPLETE ---
1. Model file save ho gayi: 'knn_friend_blueprint_model.pkl'
2. Scaler file save ho gayi: 'knn_friend_blueprint_scaler.pkl'
3. Features file save ho gayi: 'knn_model_features.pkl'

Mera Jupyter Notebook ka pura safar 100% complete ho gaya hai! 🏁🎉

In [25]:
df_blueprint.head()

,User_Profession,User_Weakness,Helps_In_Need_Score,Keeps_Secrets_Rate,Backbiting_Frequency,Calls_Only_For_Help,Closest_Friends_Toxic_Count,Respects_Others,Is_Perfect_Friend
0,Business Owner,Money Management,4.5,44,11,0,3,1,0
1,Job Seeker,Money Management,5.3,40,5,1,1,1,0
2,Student,Money Management,8.7,26,3,0,2,1,1
3,Business Owner,Money Management,4.1,65,3,0,0,1,1
4,Business Owner,Anxiety/Stress,8.8,53,10,0,2,1,0